### ISSUE TITLE
Quaternion convention inconsistency

### ISSUE THREAD

**Issue by lukashermann** [pantor/affx#1]
There is an inconsistency in the quaternion convention, the constructor of `Affine` uses the wxyz convention ([https://github.com/pantor/affx/blob/main/include/affx/affine.hpp#L37](url)), but when calling `Affine.quaternion()` you are returning a quaternion in xyzw convention ([https://github.com/pantor/affx/blob/main/include/affx/affine.hpp#L126](url))

**Comment by pantor** [comment]
Hi Lukas,

thanks for pointing that out! I've now changed the order of the returning quaternion coefficients, so it should be more consistent now.
